name: Build and publish to GHCR

on:
 push:
  tags:
   - "v*.*.*" #could be v.1.0.0
 workflow_dispatch:

job:
 publish:
  runs-on: [self-hosted]
  permissions:
   contents: read
   packages: write 

  env: 
   IMAGE_NAME: myapp

  steps: 
   - name: Checkout Code 
     uses: actions/checkout@v4 

   - name: Log in GHCR 
     run: |
      echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

   - name: Build Images 
     env: 
      TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'dev' }}
     run: |
      IMAGE="ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${TAG}"
          docker build -t "$IMAGE" .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

   
   - name: Push image
      run: docker push "$IMAGE"

   - name: Also tag :latest on version tags (optional)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          LATEST="ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest"
          docker tag "$IMAGE" "$LATEST"
          docker push "$LATEST"

   - name: Output
        run: echo "Pushed $IMAGE"


      

